# Signatures
MIDI_HEADER_SIG = b"MThd"
MIDI_TRACK_SIG = b"MTrk"

META_MSG_SIG = b'\xFF'
SYSEX_MSG_SIG = b'\xF0'

# Sizes in bytes
HEADER_SIZE = 14
HEADER_SIG_SIZE = 4
HEADER_LENGTH_SIZE = 4
HEADER_FORMAT_SIZE = 2
HEADER_TRACKS_SIZE = 2
HEADER_DIVISION_SIZE = 2
TRACK_SIG_SIZE = 4
TRACK_LENGTH_SIZE = 4

META_TYPE_SIZE = 1
SEQUENCE_NUMBER_DATA_SIZE = 2
CHANNEL_PREFIX_DATA_SIZE = 1
END_OF_TRACK_DATA_SIZE = 0
TEMPO_DATA_SIZE = 3
SMTPE_OFFSET_DATA_SIZE = 5
TIME_SIG_DATA_SIZE = 4
KEY_SIG_DATA_SIZE = 2
SEQUENCER_MESSAGE_DATA_SIZE = 1

NOTE_OFF_DATA_SIZE = 2
NOTE_ON_DATA_SIZE = 2
POLY_AFTERTOUCH_DATA_SIZE= 2
CONTROLLER_CHANGE_DATA_SIZE = 2
PROGRAM_CHANGE_DATA_SIZE = 1
CHANNEL_AFTERTOUCH_DATA_SIZE = 1
PITCH_BEND_DATA_SIZE = 2


# Message start index
META_TYPE_IND = 1
SEQUENCE_NUMBER_DATA_IND = 3