# Signatures
MIDI_HEADER_SIG = b"MThd"
MIDI_TRACK_SIG = b"MTrk"

META_MSG_SIG = b'\xFF'
SYSEX_MSG_SIG = b'\xF0'

# Sizes in bytes
HEADER_SIZE = 14
HEADER_SIG_SIZE = 4
HEADER_LENGTH_SIZE = 4
HEADER_FORMAT_SIZE = 2
HEADER_TRACKS_SIZE = 2
HEADER_DIVISION_SIZE = 2
TRACK_SIG_SIZE = 4
TRACK_LENGTH_SIZE = 4

META_TYPE_SIZE = 1
SEQUENCE_NUMBER_DATA_SIZE = 2
CHANNEL_PREFIX_DATA_SIZE = 1
END_OF_TRACK_DATA_SIZE = 0
TEMPO_DATA_SIZE = 3
SMTPE_OFFSET_DATA_SIZE = 5
TIME_SIG_DATA_SIZE = 4
KEY_SIG_DATA_SIZE = 2
SEQUENCER_MESSAGE_DATA_SIZE = 1

NOTE_OFF_DATA_SIZE = 2
NOTE_ON_DATA_SIZE = 2
POLY_AFTERTOUCH_DATA_SIZE= 2
CONTROLLER_CHANGE_DATA_SIZE = 2
PROGRAM_CHANGE_DATA_SIZE = 1
CHANNEL_AFTERTOUCH_DATA_SIZE = 1
PITCH_BEND_DATA_SIZE = 2

# Notes

NOTES_PER_OCTAVE = 12
BOTTOM_OCTAVE = -2
TOP_OCTAVE = 8
BOTTOM_NOTE = "C"
TOP_NOTE = "G"
MIDDLE_C = "C4"

NOTE_NAMES = ("C", "C#", "D", "D#", "E", "F", "F#", "G", "G#", "A", "A#", "B")

# Message start index
META_TYPE_IND = 1
SEQUENCE_NUMBER_DATA_IND = 3

# Control change messages

CONTROL_CHANGE_MAP = {
    0:  "BANK_SELECT",
    1:  "MODULATION WHEEL",
    2:  "BREATH CONTROLLER",
    3:  "UNDEFINED",
    4:  "FOOT CONTROLLER",
    5:  "PORTAMENTO TIME",
    6:  "DATA ENTRY MSB",
    7:  "CHANNEL VOLUME",
    8:  "BALANCE",
    9:  "UNDEFINED",
    10: "PAN",
    11: "EXPRESSION CONTROLLER",
    12: "EFFECT CONTROL 1",
    13: "EFFECT CONTROL 2",
    14: "UNDEFINED",
    15: "UNDEFINED",
    16: "GENERAL PURPOSE CONTROLLER 1",
    17: "GENERAL PURPOSE CONTROLLER 2",
    18: "GENERAL PURPOSE CONTROLLER 3",
    19: "GENERAL PURPOSE CONTROLLER 4",
    20: "UNDEFINED",
    21: "UNDEFINED",
    22: "UNDEFINED",
    23: "UNDEFINED",
    24: "UNDEFINED",
    25: "UNDEFINED",
    26: "UNDEFINED",
    27: "UNDEFINED",
    28: "UNDEFINED",
    29: "UNDEFINED",
    30: "UNDEFINED",
    31: "UNDEFINED",
    32: "LSB FOR CONTROL 0 (BANK SELECT)",
    33: "LSB FOR CONTROL 1 (MODULATION WHEEL)",
    34: "LSB FOR CONTROL 2 (BREATH CONTROLLER)",
    35: "LSB FOR CONTROL 3 (UNDEFINED)",
    36: "LSB FOR CONTROL 4 (FOOT CONTROLLER)",
    37: "LSB FOR CONTROL 5 (PORTAMENTO TIME)",
    38: "LSB FOR CONTROL 6 (DATA ENTRY)",
    39: "LSB FOR CONTROL 7 (CHANNEL VOLUME)",
    40: "LSB FOR CONTROL 8 (BALANCE)",
    41: "LSB FOR CONTROL 9 (UNDEFINED)",
    42: "LSB FOR CONTROL 10 (PAN)",
    43: "LSB FOR CONTROL 11 (EXPRESSION CONTROLLER)",
    44: "LSB FOR CONTROL 12 (EFFECT CONTROL 1)",
    45: "LSB FOR CONTROL 13 (EFFECT CONTROL 2)",
    46: "LSB FOR CONTROL 14 (UNDEFINED)",
    47: "LSB FOR CONTROL 15 (UNDEFINED)",
    48: "LSB FOR CONTROL 16 (GENERAL PURPOSE CONTROLLER 1)",
    49: "LSB FOR CONTROL 17 (GENERAL PURPOSE CONTROLLER 2)",
    50: "LSB FOR CONTROL 18 (GENERAL PURPOSE CONTROLLER 3)",
    51: "LSB FOR CONTROL 19 (GENERAL PURPOSE CONTROLLER 4)",
    52: "LSB FOR CONTROL 20 (UNDEFINED)",
    53: "LSB FOR CONTROL 21 (UNDEFINED)",
    54: "LSB FOR CONTROL 22 (UNDEFINED)",
    55: "LSB FOR CONTROL 23 (UNDEFINED)",
    56: "LSB FOR CONTROL 24 (UNDEFINED)",
    57: "LSB FOR CONTROL 25 (UNDEFINED)",
    58: "LSB FOR CONTROL 26 (UNDEFINED)",
    59: "LSB FOR CONTROL 27 (UNDEFINED)",
    60: "LSB FOR CONTROL 28 (UNDEFINED)",
    61: "LSB FOR CONTROL 29 (UNDEFINED)",
    62: "LSB FOR CONTROL 30 (UNDEFINED)",
    63: "LSB FOR CONTROL 31 (UNDEFINED)",
    64: "DAMPER PEDAL ON/OFF (SUSTAIN)",
    65: "PORTAMENTO ON/OFF",
    66: "SOSTENUTO ON/OFF",
    67: "SOFT PEDAL ON/OFF",
    68: "LEGATO FOOTSWITCH",
    69: "HOLD 2",
    70: "SOUND CONTROLLER 1 (DEFAULT: SOUND VARIATION)",
    71: "SOUND CONTROLLER 2 (DEFAULT: TIMBRE/HAROMONIC INTENSITY)",
    72: "SOUND CONTROLLER 3 (DEFAULT: RELEASE TIME)",
    73: "SOUND CONTROLLER 4 (DEFAULT: ATTACK TIME)",
    74: "SOUND CONTROLLER 5 (DEFAULT: BRIGHTNESS)",
    75: "SOUND CONTROLLER 6 (DEFAULT: DECAY TIME)",
    76: "SOUND CONTROLLER 7 (DEFAULT: VIBRATO RATE)",
    77: "SOUND CONTROLLER 8 (DEFAULT: VIBRATO DEPTH)",
    78: "SOUND CONTROLLER 9 (DEFAULT: VIBRATO DELAY)",
    79: "SOUND CONTROLLER 10 (DEFAULT: UNDEFINED)",
    80: "GENERAL PURPOSE CONTROLLER 5",
    81: "GENERAL PURPOSE CONTROLLER 6",
    82: "GENERAL PURPOSE CONTROLLER 7",
    83: "GENERAL PURPOSE CONTROLLER 8",
    84: "PORTAMENTO CONTROL",
    85: "UNDEFINED",
    86: "UNDEFINED",
    87: "UNDEFINED",
    88: "HIGH RESOLUTION VELOCITY PREFIX",
    89: "UNDEFINED",
    90: "UNDEFINED",
    91: "EFFECTS 1 DEPTH",
    92: "EFFECTS 2 DEPTH",
    93: "EFFECTS 3 DEPTH",
    94: "EFFECTS 4 DEPTH",
    95: "EFFECTS 5 DEPTH",
    96: "DATA INCREMENT",
    97: "DATA DECREMENT",
    98: "NON-REGISTERED PARAMETER NUMBER LSB",
    99: "NON-REGISTERED PARAMETER NUMBER MSB",
    100: "UNDEFINED",
    101: "UNDEFINED",
    102: "UNDEFINED",
    103: "UNDEFINED",
    104: "UNDEFINED",
    105: "UNDEFINED",
    106: "UNDEFINED",
    107: "UNDEFINED",
    108: "UNDEFINED",
    109: "UNDEFINED",
    110: "UNDEFINED",
    111: "UNDEFINED",
    112: "UNDEFINED",
    113: "UNDEFINED",
    114: "UNDEFINED",
    115: "UNDEFINED",
    116: "UNDEFINED",
    117: "UNDEFINED",
    118: "UNDEFINED",
    119: "UNDEFINED",
    120: "ALL SOUNDS OFF",
    121: "RESET ALL CONTROLLERS",
    122: "LOCAL CONTROL ON/OFF",
    123: "ALL NOTES OFF",
    124: "OMNI MODE OFF",
    125: "OMNI MODE ON",
    126: "MONO MODE ON",
    127: "POLY MODE ON"
}

